# platform (fastboot Ubuntu Bionic)
os: linux
dist: bionic

# node target (using .nvmrc for version)
language: node_js

# github target
branches:
    only:
        - master

# install stage
install:
    - npm install
    - npm run build

# custom build stages
script:
    - npm run test
